name: Pytest

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install tox
        run: |
          echo "Installing tox"
          pip install tox
      - name: Perform static analysis and style checks
        run: |
          echo "Running lint"
          tox -e lint

  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install tox
        run: |
          echo "Installing tox"
          pip install tox
      - name: Run pytest using the version of Python in `PATH`
        run: |
          echo "Running tests"
          tox -e py
