name: Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install tox
        run: |
          echo "Installing tox"
          pip install tox

      - name: Build the docs
        run: |
          echo "Building docs"
          tox -e docs

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install tox
        run: |
          echo "Installing tox"
          pip install tox

      - name: Run doctests
        run: |
          echo "Running doctests"
          tox -e doctests
      - name: Check for broken links in the documentation
        run: |
          echo "Checking links in the docs"
          tox -e linkcheck

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install tox
        run: |
          echo "Installing tox"
          pip install tox

      - name: Build the docs
        run: |
          echo "Building docs"
          tox -e docs

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          folder: docs/_build/html # The folder the action should deploy.
